/** Glossaire KapAvenir — définitions retraite / Sécurité sociale */
const GLOSSARY_KAP_AVENIR = {
  A: [
    ['Affilié', 'Personne rattachée à un organisme de sécurité sociale devenant ainsi un assuré social.'],
    ['Âge légal de départ', 'Âge minimum pour demander sa retraite, variable selon votre année de naissance.'],
    ['Âge du taux plein automatique', 'Âge auquel vous obtenez le taux plein même sans tous vos trimestres (67 ans en général).'],
    ['Allocataire', 'Personne qui ouvre droit à une ou plusieurs allocations.'],
    ['Allocation', 'Prestation non contributive accordée pour faire face à différents besoins.'],
    ['Allocation aux adultes handicapés (AAH)', 'Prestation non contributive servie par les caisses d’allocations familiales, destinée à assurer un minimum de ressources aux adultes ayant un handicap.'],
    ['Allocation aux mères de famille (AMF)', 'Prestation non contributive attribuée aux femmes de salariés ayant élevé au moins cinq enfants. Cette allocation n’est plus attribuée depuis le 1er janvier 2008.'],
    ['Allocation aux vieux travailleurs non salariés', 'Prestation non contributive attribuée aux travailleurs non salariés âgés des professions artisanales, industrielles ou commerciales qui ont insuffisamment cotisé et ne peuvent pas avoir de pension minimale.'],
    ['Allocation aux vieux travailleurs salariés (AVTS)', 'Prestation non contributive attribuée aux travailleurs âgés qui ont insuffisamment cotisé.'],
    ['Allocation de solidarité aux personnes âgées (Aspa)', 'Allocation non contributive versée aux retraités à partir de l’âge légal du taux plein, attribuée sous conditions de résidence en France et de ressources.'],
    ['Allocation supplémentaire d’invalidité (ASI)', 'Allocation non contributive versée aux retraités n’ayant pas l’âge pour bénéficier de l’Aspa, attribuée sous conditions de résidence en France et de ressources.'],
    ['Allocation supplémentaire L. 815-2/3 (FNS)', 'Deuxième niveau de l’ancien dispositif du minimum vieillesse remplacé par l’Aspa à compter du 1er janvier 2006.'],
    ['Allocation veuvage', 'Allocation temporaire accordée avant 55 ans au conjoint survivant, sous certaines conditions relatives aux enfants et aux ressources.'],
    ['Assiette', 'Ensemble des éléments sur lesquels est calculé un impôt ou une cotisation.'],
    ['Assiette forfaitaire', 'Base fixée par la loi sur laquelle est calculé un impôt ou une cotisation.'],
    ['Assurance retraite', 'Organisme qui gère la retraite de base des salariés du privé.'],
    ['Assurance veuvage', 'Voir Allocation veuvage.'],
    ['Assurance vieillesse', 'Versement de cotisations permettant à une personne affiliée (relevant d’un régime obligatoire de base de la Sécurité sociale) de bénéficier au moment de son passage à la retraite d’une prestation vieillesse.'],
    ['Assurance volontaire', 'Versement de cotisations par une personne non affiliée afin de bénéficier de prestations de sécurité sociale.'],
    ['Assurance volontaire des parents au foyer (AVPF)', 'Versement par la Caisse d’allocations familiales (CAF) de cotisations qui permet à une personne non affiliée de bénéficier de prestations de sécurité sociale.'],
    ['Assuré social', 'Avoir la qualité d’assuré social au régime général signifie être affilié à ce régime et y avoir versé des cotisations.'],
    ['Avantage', 'Prestation contributive ou non contributive perçue par l’assuré. Synonyme : allocation, majoration, pension.'],
    ['Avantage complémentaire', 'Avantage à caractère contributif assorti à la pension : majoration enfants de 10 %, majoration pour conjoint à charge, majoration forfaitaire pour enfants, majoration pour tierce personne.'],
    ['Avantage de vieillesse', 'Prestation attribuée au titre de l’assurance vieillesse résultant d’un droit personnel ou d’un droit de réversion.'],
    ['Ayant droit', 'Personne qui tient son droit du fait de ses liens avec un assuré.'],
  ],
  B: [
    ['Bénéficiaire', 'Personne bénéficiant d’une prestation ou d’un avantage de vieillesse ou de veuvage au régime général. Synonyme : prestataire, retraité.'],
    ['Bilan retraite', 'Analyse complète de votre carrière pour estimer votre pension et identifier des optimisations.'],
  ],
  C: [
    ['Caisse de liquidation de la prestation', 'Carsat ou CGSS ayant attribué la prestation chargée de son versement, quel que soit le lieu de résidence. Synonyme : région débitrice.'],
    ['Caisse de résidence du retraité', 'Carsat ou CGSS où réside le retraité, quelle que soit la caisse chargée du versement de la pension.'],
    ['Caisse de retraite', 'Organisme qui verse votre pension (régime de base ou complémentaire).'],
    ['Carrière longue', 'Dispositif permettant de partir plus tôt si vous avez commencé à travailler jeune.'],
    ['Carsat', 'Caisse d’assurance retraite et de la santé au travail (16 caisses régionales en métropole).'],
    ['CGSS', 'Caisse générale de sécurité sociale (Guadeloupe – Guyane – Martinique – Réunion).'],
    ['Complément de pension', 'Avantage à caractère non contributif servi sous certaines conditions avec la prestation de base : majoration article L. 814-2, FNS, Aspa, ASI.'],
    ['Compte individuel', 'Compte sur lequel est enregistré la carrière de l’assuré (cotisations, salaires soumis à cotisations, périodes assimilées…).'],
    ['Congé parental d’éducation', 'Congé non rémunéré par l’employeur qui permet à un salarié de cesser son activité professionnelle durant une période établie pour élever son (ses) enfant(s).'],
    ['Contribution additionnelle de solidarité et d’autonomie (Casa)', 'Contribution créée le 1er avril 2013, assise sur les préretraites ainsi que sur les pensions de retraite et d’invalidité au profit de la Caisse nationale de solidarité pour l’autonomie (CNSA). Le critère d’assujettissement à la Casa est aligné sur celui de la CSG taux fort. L’assiette de prélèvement est identique à celle de la CSG.'],
    ['Contribution pour le remboursement de la dette sociale (CRDS)', 'Imposition de nature fiscale créée en 1996 portant sur l’ensemble des revenus d’activité, de remplacement ou du patrimoine de chaque contribuable et destinée à rembourser les sommes empruntées par le régime général pour combler son déficit.'],
    ['Contribution sociale généralisée (CSG)', 'Imposition de nature fiscale créée en 1991 portant sur l’ensemble des revenus d’activité, de remplacement ou du patrimoine de chaque contribuable et destinée à financer en partie l’assurance maladie et les prestations familiales. Le nombre de parts fiscales et le montant du revenu fiscal de référence permettent de déterminer le taux de CSG.'],
    ['Convention internationale', 'Règle de coordination applicable en matière de sécurité sociale entre les régimes de sécurité sociale en vigueur sur le territoire de la France et un ou plusieurs autres régimes étrangers.'],
    ['Coordination entre les régimes', 'Règle applicable en matière de sécurité sociale entre les régimes de base français.'],
    ['Cotisants (actif occupé)', 'Salarié versant de manière obligatoire par prélèvement sur son salaire des cotisations lui permettant de s’ouvrir des droits auprès d’un régime de retraite de la Sécurité sociale.'],
    ['Cotisation assurance maladie (Cot AM)', 'Contribution sur les retraites créée le 1er juillet 1980. Le retraité est soumis à ce prélèvement s’il ne relève pas à titre d’un régime français à l’assurance maladie.'],
    ['Cotisations', 'Versement dont une partie est à la charge du salarié et l’autre partie à celle de l’employeur assis sur le revenu professionnel et destiné au financement de la Sécurité sociale.'],
    ['Cotisations forfaitaires', 'Cotisations dont l’assiette est fixée forfaitairement.'],
    ['Cristallisation', 'Action visant à ne pas revaloriser le montant d’un avantage.'],
    ['Cotisations retraite', 'Sommes prélevées sur vos revenus pour financer votre retraite.'],
    ['Cumul emploi-retraite', 'Possibilité de travailler tout en percevant sa retraite.'],
  ],
  D: [
    ['Date d’effet', 'Date à compter de laquelle le droit à une prestation est effectif. Synonyme : point de départ, entrée en jouissance.'],
    ['Date de cristallisation', 'Date à partir de laquelle le montant de l’avantage ne sera pas revalorisé.'],
    ['Décote', 'Réduction de la pension si vous n’avez pas tous vos trimestres.'],
    ['Deuxième droit', 'Un deuxième droit est attribué à un assuré quand celui-ci est déjà bénéficiaire d’un premier droit au régime général (titulaire d’un droit personnel et attribution d’un droit de réversion, ou inversement).'],
    ['Droit contributif', 'Prestation accordée en contrepartie de cotisations.'],
    ['Droit de réversion', 'Avantage issu des droits acquis par l’assuré décédé, attribué aux conjoints et / ou ex-conjoints survivants. Synonyme : droit dérivé, pension de réversion.'],
    ['Droit dérivé', 'Voir droit de réversion.'],
    ['Droit direct', 'Droit acquis par un assuré du fait de ses propres cotisations. Synonyme : droit personnel, droit propre, pension de vieillesse, retraite personnelle.'],
    ['Droit direct pour les retraités ayant une carrière complète au régime général', 'Pension attribuée à taux plein et sans prorata de durée d’assurance au régime général.'],
    ['Droit non contributif', 'Prestation accordée sans contrepartie de cotisations.'],
    ['Droit personnel', 'Voir droit direct.'],
    ['Droit propre', 'Voir droit direct.'],
    ['Durée d’assurance', 'Nombre total de trimestres validés dans votre carrière.'],
  ],
  E: [
    ['Épargne retraite', 'Produits d’épargne permettant de compléter vos revenus à la retraite.'],
    ['Estimation indicative globale (EIG)', 'Document officiel donnant une estimation de votre future retraite.'],
  ],
  F: [
    ['Fonds de cessation anticipée d’activité des travailleurs de l’amiante (FCAATA)', 'Fonds chargé de financer par un versement aux régimes obligatoires de retraite de base concernés, les dépenses engendrées par la mise en œuvre de la mesure « amiante » de la réforme des retraites. Voir pension au titre de l’amiante.'],
    ['Fonds de solidarité vieillesse (FSV)', 'Établissement public dont la mission principale est la prise en charge des prestations non contributives d’assurance vieillesse.'],
  ],
  I: [
    ['Incapacité permanente', 'Réduction définitive de la capacité de travail d’une personne, à la suite d’un accident du travail ou d’une maladie professionnelle. Cette réduction s’exprime en taux.'],
    ['Incapacité temporaire', 'État d’une personne qui, en raison d’un accident du travail ou d’une maladie professionnelle, ne peut plus exercer d’activité professionnelle pendant une période donnée.'],
    ['Indemnité journalière', 'Prestation en espèces versée par la Caisse primaire d’assurance maladie (Cpam) au salarié pendant son arrêt de travail pour compenser la perte de salaire.'],
  ],
  L: [
    ['Liquidation de la retraite', 'Action de demander sa retraite pour déclencher le paiement.'],
    ['Liquidation unique de la retraite des régimes alignés (Lura)', 'Le dispositif de la liquidation unique des régimes alignés (Lura) prend effet le 01/07/2017. Il s’agit d’une retraite unique pour les assurés affiliés aux régimes de salariés, de salariés agricoles et ex-régime social des indépendants.'],
  ],
  M: [
    ['Majoration de pension', 'Augmentation de votre retraite (ex : pour enfants).'],
    ['Majoration de durée d’assurance pour congé parental', 'Trimestres supplémentaires accordés aux parents qui ont bénéficié d’un congé parental. Voir congé parental.'],
    ['Majoration de durée d’assurance pour enfant', 'Trimestres supplémentaires accordés aux mères ou aux pères de famille sous certaines conditions.'],
    ['Majoration forfaitaire pour charge d’enfant (MFE)', 'Avantage complémentaire de réversion pour charge d’enfant attribué sous condition d’âge et de ressources au conjoint survivant non titulaire d’un avantage de vieillesse personnel.'],
    ['Majoration pour conjoint à charge (MC)', 'Avantage complémentaire soumis à condition de ressources versé au conjoint d’un retraité. Son montant est cristallisé. La majoration pour conjoint à charge n’est plus attribuée depuis le 1er janvier 2011.'],
    ['Majoration pour enfants (ME 10%)', 'Avantage complémentaire attribué au titulaire d’un avantage personnel ou de réversion égal à 10 % lorsque l’assuré a eu ou élevé au moins trois enfants.'],
    ['Majoration pour tierce personne (MTP)', 'Avantage complémentaire attribué au titulaire d’un avantage personnel dont l’état de santé ne permet pas avant 65 ans d’accomplir seul les actes ordinaires de la vie.'],
    ['Majoration prévue à l’article L814-2 du Code de la Sécurité sociale (L. 814-2)', 'Complément de pension destiné sous condition d’âge et de ressources à porter l’avantage de vieillesse au montant de l’AVTS. Cette majoration n’est plus attribuée depuis le 1er janvier 2006.'],
    ['Maximum des pensions', 'Montant de la pension après écrêtement au plafond de la Sécurité sociale, égal à 50 % du salaire plafond de la Sécurité sociale.'],
    ['Mesure dérogatoire', 'Possibilité pour certaines catégories de salariés de demander leur retraite avant l’âge légal. Voir pension au titre de la pénibilité – pension au titre de l’amiante.'],
    ['Minimum AVTS', 'Premier niveau de l’ancien minimum vieillesse. Voir Allocation aux vieux travailleurs salariés et Majoration prévue à l’article L. 814-2.'],
    ['Minimum contributif (mico)', 'La prestation de droit direct à taux plein peut être augmentée d’une majoration visant à la porter à un montant minimum – entier ou proratisé selon le nombre de trimestres requis en fonction de la génération – et servi ou non servi en application du plafond autorisé tous régimes.'],
    ['Minimum vieillesse', 'Allocation constituée de l’Aspa (allocation de solidarité aux personnes âgées), l’ASI (allocation supplémentaire d’invalidité) et l’allocation supplémentaire (L 815 2/3 ancien dispositif).'],
    ['Montant brut', 'Montant global de la prestation avant prélèvements sociaux.'],
    ['Montant global', 'Montant de la pension du régime général après application du minimum contributif et écrêtement au plafond de la sécurité sociale, y compris les avantages complémentaires et les compléments de pension, hors régimes complémentaires et avant prélèvements sociaux.'],
  ],
  N: [
    ['Notification', 'Document administratif émis suite à la liquidation de la prestation et destiné à informer l’intéressé de la décision prise (attribution, rejet …) à l’égard de sa demande.'],
    ['Numéro d’Inscription au Répertoire (NIR)', 'Ex numéro de sécurité sociale, servant à identifier un assuré. Il est composé de 13 chiffres correspondant au genre, à l’année, au mois, au département, à la commune ou pays de naissance et à un numéro d’ordre.'],
  ],
  P: [
    ['Pension de retraite', 'Revenu versé chaque mois après votre départ.'],
    ['Pension au titre de l’amiante (Dispositif amiante)', 'Prestation attribuée au taux plein de liquidation par le régime général à partir de 60 ans à l’assuré ayant cessé toute activité professionnelle et étant titulaire de l’allocation de cessation anticipée des travailleurs de l’amiante (ATA). Les titulaires de l’ATA sont affiliés à l’assurance volontaire à compter du 1er jour du trimestre civil qui comprend le point de départ de l’ATA. Les cotisations sont à la charge du Fonds de cessation anticipée d’activité des travailleurs de l’amiante. L’affiliation prend fin le dernier jour du trimestre civil qui précède le point de départ de la retraite.'],
    ['Pension au titre de la pénibilité', 'Prestation attribuée au taux plein de liquidation par le régime général à partir de 60 ans à tout assuré titulaire auprès de la Caisse primaire d’assurance maladie d’une rente d’incapacité permanente au titre d’une maladie professionnelle ou d’un accident de travail.'],
    ['Pension d’invalidité', 'Prestation attribuée par la Cpam (la Cramif pour l’Île-de-France) avant l’âge légal du droit à la retraite à un assuré dont la capacité de travail ou de gain est réduite d’au moins deux tiers, constatée médicalement.'],
    ['Pension d’invalidité de veuf ou de veuve (PIVV)', 'Prestation accordée par la Caisse primaire d’assurance maladie à tout survivant invalide âgé de moins de 55 ans.'],
    ['Pension de réversion', 'Voir droit de réversion.'],
    ['Pension de vieillesse', 'Voir droit direct.'],
    ['Pension de vieillesse à titre d’Ex-Invalide', 'Prestation au taux plein de liquidation attribuée par le régime général à partir de l’âge légal de départ à la retraite à tout bénéficiaire d’une pension d’invalidité servie au préalable par la Caisse primaire d’assurance maladie (la Cramif pour l’Île-de-France).'],
    ['Pension de vieillesse de veuf ou de veuve (PVV)', 'Prestation attribuée par le régime général en remplacement de la PIVV dès l’âge de 55 ans au conjoint survivant d’un assuré décédé bénéficiaire ou susceptible de bénéficier d’une pension d’invalidité. À l’âge légal de départ à la retraite, l’assuré sera en droit de percevoir une pension de vieillesse à titre d’Ex-invalide.'],
    ['Pension pour inaptitude au travail', 'Prestation attribuée au taux plein de liquidation par le régime général à partir de l’âge légal de départ à la retraite à tout assuré ayant une capacité de travail ou de gain réduite de 50 %, médicalement constatée.'],
    ['Période assimilée (PA)', 'La période assimilée au régime général est issue de l’interruption involontaire de l’activité professionnelle (chômage, maladie …). Cette période fait l’objet d’un report de trimestre au compte individuel de l’assuré.'],
    ['Période reconnue équivalente', 'Toute période d’activité professionnelle : non cotisée au régime général exercée avant le 1er avril 1983 en France ou à l’étranger qui peut ou aurait pu être rachetée au titre de l’assurance vieillesse, ou non-salariée agricole exercée entre 18 et 21 ans avant le 1er avril 1976 sans versement de cotisations, non-salariée artisanale, industrielle ou commerciale exercée avant le 1er avril 1983 par un membre de la famille du chef d’entreprise. Ces périodes sont prises en compte uniquement pour calculer le taux de la retraite.'],
    ['Période validée par présomption', 'Toute période validée sous certaines conditions en l’absence de preuves de précompte ou d’indemnisation. Il peut s’agir de périodes d’activités ou de périodes assimilées. Seuls les trimestres (sans salaires) sont reportés au compte de l’assuré.'],
    ['Plafond de la Sécurité sociale (PASS)', 'Montant de référence utilisé pour calculer certaines cotisations et droits.'],
    ['Plafond de ressources', 'Limite de ressources au-delà de laquelle le droit à certains avantages complémentaires et compléments de pension est non attribué, réduit ou supprimé.'],
    ['Points retraite', 'Unités utilisées pour calculer la retraite complémentaire.'],
    ['Polypensionné', 'Retraité ayant cotisé durant sa carrière professionnelle auprès d’au moins deux régimes. Les régimes alignés (régime général, MSA et travailleurs indépendants) sont considérés comme un seul régime (LURA).'],
    ['Premier droit', 'Un premier droit (1er droit) est un nouvel entrant de droit direct ou dérivé au régime général. Voir deuxième droit.'],
    ['Prestataire', 'Voir bénéficiaire.'],
    ['Prestation vieillesse', 'Voir pension.'],
    ['PRISME (Projection des Retraites Individuelles Simulation, Modélisation, Évaluation)', 'Modèle de microsimulation dynamique, qui sert à simuler au niveau individuel et dans le temps, les départs en retraite en fonction des évolutions économiques et législatives.'],
  ],
  R: [
    ['Rachat de trimestres', 'Paiement volontaire pour compléter des trimestres manquants.'],
    ['Rappel', 'Mise en paiement en une seule fois de plusieurs mensualités (dans la limite de 5 ans) dues à un assuré à l’occasion de la révision de son dossier.'],
    ['Régime de base', 'Retraite obligatoire principale.'],
    ['Régime complémentaire', 'Retraite qui s’ajoute au régime de base.'],
    ['Régime général', 'Régime de base obligatoire des salariés du commerce, de l’industrie et des services.'],
    ['Régime spécial', 'Régime qui bénéficie d’une totale autonomie de gestion par rapport aux autres régimes de Sécurité Sociale pour l’assurance maladie et l’assurance vieillesse.'],
    ['Relevé de carrière', 'Document récapitulant votre carrière et vos trimestres.'],
    ['Rétablissement dans les droits', 'Les fonctionnaires radiés après le 28 janvier 1950 sont rétablis dans les droits qu’ils auraient eus si le régime général leur avait été applicable dès lors qu’ils quittent le régime spécial sans droit à pension.'],
    ['Retraite anticipée', 'Retraite attribuée avant l’âge légal sous certaines conditions pour « longue carrière » ou au titre « assuré handicapé » ou au profit de certains « travailleurs handicapés ».'],
    ['Retraite au titre de la pénibilité', 'L’assuré atteint d’une incapacité permanente a droit à la retraite au titre de la pénibilité dès 60 ans, quelle que soit sa durée d’assurance, sous réserve de l’avis du médecin-conseil et de la commission pluridisciplinaire qui statue.'],
    ['Retraite progressive', 'Dispositif permettant de réduire son activité tout en touchant une partie de sa retraite.'],
    ['Rétroactivité', 'Possibilité de tenir compte d’une date passée, liée à un fait précis dans la démarche d’un assuré en vue de faire valoir ses droits pour déterminer le point de départ d’une prestation, d’un avantage complémentaire ou d’un complément de pension.'],
    ['Revalorisation', 'Opération visant à ajuster les pensions, rentes, salaires ou cotisations en fonction de l’évolution des salaires ou des prix.'],
  ],
  S: [
    ['Salaire annuel moyen (SAM)', 'Moyenne des meilleures années de salaire servant au calcul de la retraite.'],
    ['Salaire minimum interprofessionnel de croissance (SMIC)', 'Rémunération horaire minimum due à tout salarié.'],
    ['Salaire plafond soumis à cotisations de sécurité sociale', 'Montant maximum soumis à cotisations salariales d’assurance vieillesse. Le montant du salaire versé au-delà de ce plafond n’est pas soumis à la cotisation d’assurance vieillesse pour la part salariale.'],
    ['Secours viager', 'Allocation attribuée au conjoint survivant d’un assuré décédé titulaire ou susceptible de l’être de l’allocation aux vieux travailleurs salariés. Le secours viager n’est plus attribué depuis le 1er janvier 2006.'],
    ['Surcote', 'Augmentation de la pension si vous continuez à travailler après le taux plein.'],
  ],
  T: [
    ['Taux de liquidation', 'Pourcentage de calcul appliqué au salaire annuel moyen de base.'],
    ['Taux plein', 'Taux maximum appliqué au calcul de la retraite.'],
    ['Trimestre', 'Unité de mesure de la durée de cotisation.'],
    ['Terme à échoir', 'Montant payé au début de la période pour laquelle il est dû.'],
    ['Terme échu', 'Montant payé à la fin de la période pour laquelle il est dû.'],
    ['Trimestre assimilé', 'Voir période assimilée.'],
    ['Trimestre civil', 'Période de 3 mois consécutifs débutant les 1er janvier, 1er avril, 1er juillet et 1er octobre.'],
  ],
  V: [
    ['Validation des trimestres', 'Acquisition de trimestres grâce au travail ou à certaines périodes (chômage, maladie…).'],
    ['Versement forfaitaire unique (VFU)', 'Capital égal à 15 fois le montant annuel de la pension de vieillesse lorsque cette pension annuelle (y compris les avantages complémentaires) est inférieure à un montant minimum fixé par arrêté.'],
  ],
};

export default GLOSSARY_KAP_AVENIR;
